### ISSUE TITLE
Have a smart meter but no gateway?

### ISSUE THREAD

**Issue by Junkbite** [mjmeli/pyduke-energy#15]
I called Duke to ask them to add a gateway and customer support had no idea what I was talking about. They said I do have a smart meter and I can view my daily usage on my account but this library doesnt work. Is there another name for this "gateway"?

**Comment by lshep5801** [comment]
Helpful information in this link:

https://www.reddit.com/r/homeassistant/comments/oxxdou/duke_energy_smart_gateway/

Pointers and links on how to apply.

**Comment by Junkbite** [comment]
link is dead

**Comment by lshep5801** [comment]
Sorry.  I think this was the link I used just last week and it worked.

**Comment by mjmeli** [comment]
Link looks live now, reddit was down yesterday.

If you don't have the gateway, the only data you have available via the app is your daily usage in the past. In other words, the most recent data you can get is yesterday's. This means no real time usage and no current day usage. Without either of these things, you can't use the energy dashboard. As such, this library doesn't support that and I don't have plans to.

I'm not sure why support isn't knowledgeable of it, but it is a pilot program and I don't think anyone knows the availability. You might can try that Reddit thread which has pointers to getting to the sign up page, but if you weren't explicitly invited then I wouldn't count on being able to get in.
