### ISSUE TITLE
Server Error on login

### ISSUE THREAD

**Issue by CmpCtrl** [mjmeli/pyduke-energy#23]
I noticed on 5/23 that i could not login, i was receiving `pyduke_energy.errors.RequestError: Request failed with unexpected error [https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token]: (ClientResponseError) 500, message='Internal Server Error', url=URL('https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token')`. 

I also could not login from the app. Today 5/24 i see that the app works again and an update from 5/23 has a changelog of "This version resolves Android login issues that started 5/22/2022". Curious. 

I haven't had a chance to look into it yet.

**Comment by mjmeli** [comment]
They updated the basic auth digest used on the OAuth login request. Will push a fix
