### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by CmpCtrl** [mjmeli/pyduke-energy#5]
The API has been down most of the week of 11/1 with a message about system maintenance in the mobile app. Today the mobile app is working again, but I'm getting 404 errors when trying to connect. Have you seen the same? I'll try to investigate further later on.

```
Request failed with unexpected error [https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token]: 404, message='Not Found', url=URL('https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token')
```

**Comment by mjmeli** [comment]
The 404 errors stopped for me today after the site and app came back up. Let me know if you find anything

**Comment by CmpCtrl** [comment]
Ok, it seems like I locked my account with bad login attempts which was then giving me the 404 error. Not sure if there's a better way to handle that, but no changes are needed. 

On a separate note, I notice that your latest release has all the logging bumped down to `debug` level, but i don't see any `info` level logging. Why not leave some msgs in the info level? I like to have some feedback when its running continually, but the debug level has too much to be useful. 

If you're trying to avoid msgs from this library in another script that is using it, one trick i've used elsewhere is to set the logging level for that library higher. For instance `logging.getLogger("pyduke-energy").setLevel(logging.WARNING)`

**Comment by mjmeli** [comment]
I didn't feel like some of those needed to be info vs debug as they seemed like debug messages too so I was trying to be consistent there. I can see them being useful for that so I can switch them back to info if you want. Are there ones in particular that are more useful? Or maybe we could implement an optional callback that you could hook your own looking in. 

These were the ones I changed 8756f535438fe4dcb49bbebbf80585e2ceb81924

**Comment by CmpCtrl** [comment]
Copy, yea I could certainly subclass some of these to add in the logging. 

I think my favorites to glance at the terminal and see that its running correctly are the subscribed, line 88, unsubscribed, 104, disconnected, 126, and the multiple msg timeout, 228 ( tho you could make a case for that being a warning). 

I made a quick branch in my fork to add these back in for myself, so feel free to not add them into your release. Thanks,
